name: CI

on:
  push:
    branches:
      - main
      - "feature/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Start Selenoid
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: Checkout the code
        uses: actions/checkout@v2

      - name : Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name : Deps install
        run : npm install

      - name : Run tests
        run : npm test
      
      - name : Test Reports
        uses: dorny/test-reporter@v1
        with:
          name: WDIO Tests
          path: junit-report/**.xml
          reporter: java-junit
          
      - name: Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
